# seems that travis supports D, using dub with various compilers
language: d

d:
  - dmd
  - dmd-2.068.2
  - ldc
  - gdc

before_install:
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
 - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libev libevent sqlite; fi"

os:
 - linux
 - osx

sudo: false

script: dub build

addons:
  apt:
    packages:
    - libev-dev
    - libevent-dev
    - libsqlite3-dev

# only the most recent versions of dmd currently work as both ldc and gdc have not been updated to use new D features.
matrix:
  allow_failures:
    - d: ldc
    - d: gdc
