# travis-ci.org supports D, using dub with various compilers
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.072.2
  - dmd-2.071.1
  - ldc-1.1.0-beta6
  - ldc-1.0.0
  - gdc

# use OSX 10.11 rather than default (10.9). see: https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version
osx_image: xcode7.3

before_install:
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libev libevent openssl sqlite && brew link --force sqlite; fi"

install:
  - npm install -g bower

os:
  - linux
  - osx

script:
  - dub test --compiler=${DC}

addons:
  apt:
    packages: [ libev-dev, libevent-dev, libsqlite3-dev ]

matrix:
  include:
    - env: NAME="Test Coverage - coveralls.io"
      d: dmd
      os: osx
      script: dub fetch doveralls && dub test -b unittest-cov --compiler=${DC}
      after_success: dub run doveralls
  allow_failures:
    - d: gdc
