# travis-ci.org supports D, using dub with various compilers
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - ldc
  - gdc

before_install:
  - npm install -g bower
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libev libevent sqlite && brew link --force sqlite; fi"

# removed test coverage until can get 'dub test -b unittest-cov --compiler=${DC}' working
#install:
#  - wget -O doveralls "https://github.com/ColdenCullen/doveralls/releases/download/v1.1.5/doveralls_linux_travis"
#  - chmod +x doveralls

os:
  - linux
  - osx

script:
  - dub test --compiler=${DC}


addons:
  apt:
    packages: [ libev-dev, libevent-dev, libsqlite3-dev ]

# GDC lags behind DMD
matrix:
  include:
    - d: dmd
      os: linux
      script: dub test --coverage --combined --compiler=${DC}
      install: dub fetch doveralls
      after_success: dub run doveralls
  allow_failures:
    - d: gdc
