# travis-ci.org supports D, using dub with various compilers
language: d

d:
  - ldc
  - dmd
  - dmd-2.087.0
  - dmd-2.086.1
  - dmd-2.085.1
  - ldc-1.17.0 # eq to dmd v2.087
  - ldc-1.16.0 # eq to dmd v2.086.1
  - ldc-1.15.0 # eq to dmd v2.085.1
  - gdc

install:
  - npm install -g bower

os:
  - linux
  - osx

script:
  - dub test --compiler=${DC}

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages: [ libev-dev, libevent-dev, libsqlite3-dev ]
  homebrew:
    brewfile: true

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - env: NAME="Test Coverage - coveralls.io"
      d: dmd
      os: osx
      before_script: dub fetch doveralls && dub test -b unittest-cov --compiler=${DC}
      script: dub run doveralls
  allow_failures:
    - d: gdc
