# travis-ci.org supports D, using dub with various compilers
# For available compilers see: https://semitwist.com/travis-d-compilers
language: d

d:
  - ldc
  - dmd
  - dmd-2.094.2
  - dmd-2.093.1
  - dmd-2.092.1
  - dmd-2.091.1
  - ldc-1.24.0 # eq to dmd v2.094.1
  - ldc-1.23.0 # eq to dmd v2.093.1
  - ldc-1.22.0 # eq to dmd v2.092.1
  - ldc-1.21.0 # eq to dmd v2.091.1

install:
  - npm install -g bower

script:
  - dub test --compiler=${DC}

addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages: [ libev-dev, libevent-dev, libsqlite3-dev ]
  homebrew:
    brewfile: true

cache:
  yarn: true
  directories:
    - node_modules

matrix:
  include:
    - env: NAME="Test Coverage - coveralls.io"
      d: dmd
      os: osx
      osx_image: xcode12.2 # use OSX 10.15.7
      before_script: dub fetch doveralls && dub test -b unittest-cov --compiler=${DC}
      script: dub run doveralls
    - d: dmd
      os: osx
      osx_image: xcode12.2 # use OSX 10.15.7
    - d: ldc
      os: osx
      osx_image: xcode12.2 # use OSX 10.15.7
    - d: dmd-beta
    - d: gdc
  allow_failures:
    - d: dmd-beta
    - d: gdc
