language: d

d:
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.067.1
  - dmd-2.066.1
  - ldc-0.16.1
  - ldc-0.15.1
  - gdc-5.2.0
  - gdc-4.9.2

os:
 - linux
 - osx
 
sudo: false

addons:
  apt:
    packages:
    - libev-dev