# travis-ci.org supports D, using dub with various compilers
language: d

sudo: required
dist: trusty

d:
  - dmd
  - dmd-2.069.2
  - ldc
  - gdc

before_install:
  - npm install -g bower
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew update; fi"
  - "if [ ${TRAVIS_OS_NAME} = 'osx' ]; then brew install libev libevent sqlite && brew link --force sqlite; fi"
  - wget http://bit.ly/Doveralls | bash

os:
  - linux
  - osx

script:
  - dub test -b unittest-cov
  - ./doveralls

addons:
  apt:
    packages: [ libev-dev, libevent-dev, libsqlite3-dev ]

# GDC lags behind DMD
matrix:
  allow_failures:
    - d: gdc
