name: dub test

on:
  schedule:
    - cron: '30 7 1 * *'
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    name: ${{ matrix.compiler }} on ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ] # don't bother with windows-latest or macOS-latest
        compiler:
          - dmd-latest
          - ldc-latest
          - dmd-2.096.1
          - dmd-2.095.1
          - dmd-2.094.2
          - dmd-2.093.1
          - dmd-2.092.1
          - dmd-2.091.1
          # - ldc-1.25.1 # eq to dmd v2.095.1 ## Fails for some reason
          - ldc-1.24.0 # eq to dmd v2.094.1
          - ldc-1.23.0 # eq to dmd v2.093.1
          - ldc-1.22.0 # eq to dmd v2.092.1
          - ldc-1.21.0 # eq to dmd v2.091.1
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2

      - name: Install D ${{ matrix.compiler }}
        uses: dlang-community/setup-dlang@v1
        with:
          compiler: ${{ matrix.compiler }}

      - name: Install dependencies on Ubuntu
        if: startsWith(matrix.os, 'ubuntu')
        run: sudo apt-get update && sudo apt-get install libev-dev libevent-dev libsqlite3-dev -y

      # - name: Install dependencies on Mac OSX
      #   if: startsWith(matrix.os, 'mac')
      #   run: brew bundle

      - name: build and run the unittest config
        run: dub test